# Create all necessary directories for WAVECOREERP

$root = "C:\Users\HomePC\Desktop\WAVECOREERP\wavecoreerp"

# Root level directories
$dirs = @(
    ".github\workflows",
    "apps\web\src\app\(auth)\login",
    "apps\web\src\app\(auth)\register",
    "apps\web\src\app\(dashboard)\dashboard",
    "apps\web\src\app\(dashboard)\pos\terminal",
    "apps\web\src\app\(dashboard)\pos\sales",
    "apps\web\src\app\(dashboard)\inventory\products\[id]",
    "apps\web\src\app\(dashboard)\inventory\categories",
    "apps\web\src\app\(dashboard)\inventory\brands",
    "apps\web\src\app\(dashboard)\inventory\warehouses",
    "apps\web\src\app\(dashboard)\crm\customers\[id]",
    "apps\web\src\app\(dashboard)\crm\leads",
    "apps\web\src\app\(dashboard)\crm\loyalty",
    "apps\web\src\app\(dashboard)\accounting\chart-of-accounts",
    "apps\web\src\app\(dashboard)\accounting\journal-entries",
    "apps\web\src\app\(dashboard)\accounting\invoices",
    "apps\web\src\app\(dashboard)\accounting\expenses",
    "apps\web\src\app\(dashboard)\accounting\financial-statements",
    "apps\web\src\app\(dashboard)\hrm\employees\[id]",
    "apps\web\src\app\(dashboard)\hrm\attendance",
    "apps\web\src\app\(dashboard)\hrm\leave",
    "apps\web\src\app\(dashboard)\hrm\payroll",
    "apps\web\src\app\(dashboard)\procurement\suppliers\[id]",
    "apps\web\src\app\(dashboard)\procurement\purchase-orders",
    "apps\web\src\app\(dashboard)\analytics",
    "apps\web\src\app\(dashboard)\reports",
    "apps\web\src\app\(dashboard)\ai-copilot",
    "apps\web\src\app\(dashboard)\ecommerce",
    "apps\web\src\app\(dashboard)\settings\subscription",
    "apps\web\src\app\(dashboard)\settings\users",
    "apps\web\src\components\ui",
    "apps\web\src\components\layout",
    "apps\web\src\components\shared",
    "apps\web\src\components\modules\inventory",
    "apps\web\src\components\modules\pos",
    "apps\web\src\components\modules\ai",
    "apps\web\src\lib",
    "apps\web\src\stores",
    "apps\web\src\hooks",
    "apps\web\src\types",
    "apps\web\src\styles",
    "apps\web\public\images\icons",
    "apps\web\public\fonts",
    "apps\api\src\config",
    "apps\api\src\common\decorators",
    "apps\api\src\common\guards",
    "apps\api\src\common\interceptors",
    "apps\api\src\common\filters",
    "apps\api\src\common\pipes",
    "apps\api\src\common\middleware",
    "apps\api\src\common\interfaces",
    "apps\api\src\prisma",
    "apps\api\src\modules\auth\strategies",
    "apps\api\src\modules\auth\guards",
    "apps\api\src\modules\auth\dto",
    "apps\api\src\modules\auth\services",
    "apps\api\src\modules\tenant\dto",
    "apps\api\src\modules\users\dto",
    "apps\api\src\modules\inventory\products\dto",
    "apps\api\src\modules\inventory\categories",
    "apps\api\src\modules\inventory\brands",
    "apps\api\src\modules\inventory\warehouses",
    "apps\api\src\modules\inventory\stock",
    "apps\api\src\modules\inventory\batches",
    "apps\api\src\modules\pos\dto",
    "apps\api\src\modules\crm\customers",
    "apps\api\src\modules\crm\leads",
    "apps\api\src\modules\crm\loyalty",
    "apps\api\src\modules\accounting\accounts",
    "apps\api\src\modules\accounting\journal-entries",
    "apps\api\src\modules\accounting\invoices",
    "apps\api\src\modules\accounting\expenses",
    "apps\api\src\modules\hrm\employees",
    "apps\api\src\modules\hrm\attendance",
    "apps\api\src\modules\hrm\leave",
    "apps\api\src\modules\hrm\payroll",
    "apps\api\src\modules\procurement\suppliers",
    "apps\api\src\modules\procurement\purchase-orders",
    "apps\api\src\modules\payments\mpesa",
    "apps\api\src\modules\payments\stripe",
    "apps\api\src\modules\payments\flutterwave",
    "apps\api\src\modules\subscription",
    "apps\api\src\modules\ai\agents",
    "apps\api\src\modules\ai\providers",
    "apps\api\src\modules\analytics",
    "apps\api\src\modules\ecommerce\orders",
    "apps\api\src\modules\ecommerce\store",
    "apps\api\src\modules\reports",
    "apps\api\src\modules\webhooks",
    "apps\api\src\graphql\resolvers",
    "apps\api\test",
    "packages\shared\src\types",
    "packages\shared\src\utils",
    "packages\shared\src\constants",
    "packages\ui\src\components",
    "packages\config\src",
    "infrastructure\docker",
    "infrastructure\kubernetes",
    "infrastructure\terraform\modules\vpc",
    "infrastructure\terraform\modules\eks",
    "infrastructure\scripts",
    "docs"
)

foreach ($dir in $dirs) {
    $path = Join-Path $root $dir
    New-Item -ItemType Directory -Force -Path $path | Out-Null
    Write-Host "Created: $dir"
}

Write-Host ""
Write-Host "============================================"
Write-Host " ALL FOLDERS CREATED SUCCESSFULLY!"
Write-Host "============================================"
Write-Host ""
Write-Host "Now place all the generated files into their folders."
Write-Host "Then run: pnpm install && cd apps/api && npx prisma generate && npx prisma db push && cd ../.. && pnpm dev"